### ISSUE TITLE
Update Travis build due to API break with xfvb

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-vscode#102]
0.00s$ sh -e /etc/init.d/xvfb start
sh: 0: Can't open /etc/init.d/xvfb
The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .

https://benlimmer.com/2019/01/14/travis-ci-xvfb/

**Comment by djelinek** [comment]
verified with master branch
