### ISSUE TITLE
Move to Red Hat publisher

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-vscode#107]
- remove publish from Travis config
- change icon
- change publisher in package.json
- provide jenkins pipeline config (example here https://github.com/redhat-developer/vscode-project-initializer/blob/master/Jenkinsfile)

**Comment by apupier** [comment]
created job on jenkins CI (not yet working) https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/VS Code/job/vscode-apache-camel_release currently configured on my branch https://github.com/apupier/camel-lsp-client-vscode/tree/107-movepublishToRedHat

**Comment by djelinek** [comment]
verified with master branch
