### ISSUE TITLE
[Regression]Diagnostics for Camel URIs is not working

### ISSUE THREAD

**Issue by djelinek** [camel-tooling/camel-lsp-client-vscode#142]
**Environment**
- latest build of LSP server 1.1.0-SNAPSHOT
- VS Code 1.38.1
- Language Support for Apache Camel by Red Hat - latest 0.0.18

**Tested code**:
```
<camelContext id="uitest-context" xmlns="http://camel.apache.org/schema/spring">
    <route id="uitest-route">
        <from id="_fromID" uri="timer:timerName?delay=1000r"/>
    </route>
</camelContext>
```

**Result**:
no detected errors in Problems view

**Comment by apupier** [comment]
this is a regression coming from Language Server. It is affecting only unreleased VS Code extension.

**Comment by djelinek** [comment]
verified - latest build of LSP server 1.1.0-SNAPSHOT
