### ISSUE TITLE
Activate Sonar analysis

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-vscode#19]

**Comment by apupier** [comment]
not working, on master there is this error:
![image](https://user-images.githubusercontent.com/1105127/39245187-4277b174-4893-11e8-9a3f-2db1544db646.png)
but there is no line 58 in travis.yml file, don't know which file it is talking about...

**Comment by lhein** [comment]
haven't seen it myself. Seems u lack the ; behind your sonar call

**Comment by lhein** [comment]
you have to have the ; in order to have the "fi" recognized

**Comment by apupier** [comment]
> you have to have the ; in order to have the "fi" recognized

argh, thanks, i will provide another PR

**Comment by lhein** [comment]
already done in #24
