### ISSUE TITLE
Avoid forcing a new "version" in code for pushing a new version to VSCode marketplace

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-vscode#21]

**Comment by apupier** [comment]
looking to what vscode-yaml is doing might be a good idea: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/vscode-yaml.release/

**Comment by lhein** [comment]
the current logic needs a tag to be pushed and the versions to be adjusted manually.

**Comment by apupier** [comment]
this has been completely reworked and is now outdated
