### ISSUE TITLE
Suggestion: detail current features

### ISSUE THREAD

**Issue by paoloantinori** [camel-tooling/camel-lsp-client-vscode#25]
Hi, I have installed vscode plugin but I'm struggling to understand what features the plugin has and where I should see its behavior kicking in.

I would like to read a more explicit list of currently supported features. For example:
- which DSL are supported? (java/xml/blueprint/whatever)
- does the autocompletion kick in while I'm editing an endpoint URI ?
- anything else?

A quick video might be good to show case the features, but personally I'd like to see these feature in form of a quick cropped screenshot that can give me, with a glimpse of an eye, all the information that I need.

thank you

**Comment by apupier** [comment]
For information before improving readme:

> which DSL are supported? (java/xml/blueprint/whatever)

Only XML DSL for now.
We hope Java DSL too in future: https://github.com/camel-tooling/camel-language-server/issues/6

> does the autocompletion kick in while I'm editing an endpoint URI ?

yes

> anything else?

it also provides documentation on hover
see (very brief for now) https://github.com/camel-tooling/camel-language-server#features
