### ISSUE TITLE
download of the server jar fails with 404

### ISSUE THREAD

**Issue by lhein** [camel-tooling/camel-lsp-client-vscode#5]

**Comment by apupier** [comment]
the url to download was based on published artefacts in previous repository. The URL need to be updated.
When the artefact will be published on a maven repo, it will be better to use the maven coordinates

**Comment by lhein** [comment]
the url is valid and working in a browser

**Comment by apupier** [comment]
the URL is not the correct one, a redirection is automatically done by the browser but not by the js library
