### ISSUE TITLE
Log error when something wrong happen

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-vscode#73]
for instance "languageClient.onReady().then" doesn't contain handling of error callback

it will be particularly useful for checking what is working/not working with this VSCode plugin inside Theia https://github.com/eclipse/che/issues/11705

**Comment by djelinek** [comment]
@apupier where in VS Code are error logged? I see errors only for `.java` (not for `.xml`) files inside `Problems` part of editor

**Comment by apupier** [comment]
this enhancement is to report errors in console when the language Server is failing to start completely.

So I'm not sure which error you see for .java that you don't see for .xml. Can you open a dedicated issue for that please?

**Comment by djelinek** [comment]
ok, it is working. I badly understood this issue description.

I will more investigate .xml vs .java error reporting problem and eventually I will open dedicated issue.

**Comment by djelinek** [comment]
verified - `camel-lsp-server-1.1.0-SNAPSHOT`
