### ISSUE TITLE
DSL Language Support is not working for Apache Camel K on VS Code

### ISSUE THREAD

**Issue by gurutata** [camel-tooling/camel-lsp-client-vscode#921]
As per the instructions given in the documentation of [Language Support for Apache Camel by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-apache-camel&ssr=false#qna), I have configured my VS Code. JDK 11 is what I have installed and configured on my machine. I have my Kamel K version 1.8.2 is installed and Minikube is up and running on the Docker platform. 

on the ctrl+tab it is not loading the API/Language suggestions for Camel K DSL language.
Verified the Settings of the Camel K tooling/Language. Everything seems correct
![Screen-1](https://user-images.githubusercontent.com/93941155/158046232-daac358d-1675-4501-b974-295a7e26f331.png)
![Screen-2](https://user-images.githubusercontent.com/93941155/158046233-9b302a8f-4897-4f73-b7f9-dd1b2e482528.png)
.

> DSL Language Support is not working for Apache Camel K on VS Code

**Comment by apupier** [comment]
The mentioned Camel K command is part of [VS Code tooling support for  Camel K](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-camelk) extension, not [VS Code Language Support for Apache Camel](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-apache-camel)

The java completion requires both [VS Code tooling support for  Camel K](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-camelk)  and [VS code Language Support for Java](https://marketplace.visualstudio.com/items?itemName=redhat.java).

The easiest might be to use the [Extension pack for Apache Camel](https://marketplace.visualstudio.com/items?itemName=redhat.apache-camel-extension-pack) which is coming with the required extensions

**Comment by gurutata** [comment]
Hi, @apupier Thank you for your response to my query. I have the complete setup done as you mentioned above besides, I have also tried with different JDK versions. however, still, the language support for Camel is not working and It throws an error while using the commands as shown in my previous post screenshot.

Regards,
Guru

**Comment by apupier** [comment]
Can you precise:
- the version of each extension
- the VS Code version

Can you check the logs (View -> output):
- Apache Camel K
- Language Support for Java
- Language Support for Apache Camel
- Log ( * ), especially Log (Extension host) to check that the mentioned extension activated succesfully

Can you precise when you have the command not found, after calling it from command palette? When clicking in a tutorial link? Another way?

**Comment by apupier** [comment]
@gurutata Do you have more information to share? Or is it working for you now?

**Comment by apupier** [comment]
closing as we are missing information to investigate more. Please reopen if you have more details.
