### ISSUE TITLE
Loading YAML fails

### ISSUE THREAD

**Issue by sidharthramesh** [camel-tooling/camel-lsp-client-vscode#993]
# Issue information

## **BUG** report
Getting this error on opening a YAML file:
```
Unable to load schema from 'https://raw.githubusercontent.com/apache/camel/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json': Request vscode/content failed unexpectedly without providing any details.
```

### Environment

- Language Support for Apache Camel version: "**v0.0.12**" ?
- OS:
    - [ ] Linux (*RHEL*, *Fedora*, *Ubuntu*, ...)
    - [ ] Windows
    - [x] macOS

### Exact steps to reproduce issue

1. Open any YAML file with Camel K annotation

### Expected behaviour

No errors

### Screenshot (*optional*)
<img width="841" alt="image" src="https://user-images.githubusercontent.com/18082719/174466731-5a94ff10-fc3d-4ab7-9295-89b05af09f4d.png">

Related to this new commit: https://github.com/apache/camel/commit/2810899cf31af7dd1d1ef6a601578e6273ac83fa#diff-8ae88cdbf87feb93434af4047cf53a70b3eb99d83bc2403cc8da60d24d6976d5

**Comment by davsclaus** [comment]
PR to move the schema from the schema store
https://github.com/SchemaStore/schemastore/pull/2305

**Comment by apupier** [comment]
Fixed in Schemastore.
